/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Style = IDL.Variant({
  'fluent' : IDL.Null,
  'simple' : IDL.Null,
  'eloquent' : IDL.Null,
});
export const IntensityLevel = IDL.Variant({
  'low' : IDL.Null,
  'normal' : IDL.Null,
  'high' : IDL.Null,
  'extreme' : IDL.Null,
});
export const Preferences = IDL.Record({
  'style' : Style,
  'intensityLevel' : IntensityLevel,
});

export const idlService = IDL.Service({
  'getPreferences' : IDL.Func([], [Preferences], ['query']),
  'updatePreferences' : IDL.Func([Style, IntensityLevel], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Style = IDL.Variant({
    'fluent' : IDL.Null,
    'simple' : IDL.Null,
    'eloquent' : IDL.Null,
  });
  const IntensityLevel = IDL.Variant({
    'low' : IDL.Null,
    'normal' : IDL.Null,
    'high' : IDL.Null,
    'extreme' : IDL.Null,
  });
  const Preferences = IDL.Record({
    'style' : Style,
    'intensityLevel' : IntensityLevel,
  });
  
  return IDL.Service({
    'getPreferences' : IDL.Func([], [Preferences], ['query']),
    'updatePreferences' : IDL.Func([Style, IntensityLevel], [], []),
  });
};

export const init = ({ IDL }) => { return []; };