/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type IntensityLevel = { 'low' : null } |
  { 'normal' : null } |
  { 'high' : null } |
  { 'extreme' : null };
export interface Preferences {
  'style' : Style,
  'intensityLevel' : IntensityLevel,
}
export type Style = { 'fluent' : null } |
  { 'simple' : null } |
  { 'eloquent' : null };
export interface _SERVICE {
  'getPreferences' : ActorMethod<[], Preferences>,
  'updatePreferences' : ActorMethod<[Style, IntensityLevel], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];