/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Preferences {
    style: Style;
    intensityLevel: IntensityLevel;
}
export enum IntensityLevel {
    low = "low",
    normal = "normal",
    high = "high",
    extreme = "extreme"
}
export enum Style {
    fluent = "fluent",
    simple = "simple",
    eloquent = "eloquent"
}
export interface backendInterface {
    getPreferences(): Promise<Preferences>;
    updatePreferences(style: Style, intensityLevel: IntensityLevel): Promise<void>;
}
import type { IntensityLevel as _IntensityLevel, Preferences as _Preferences, Style as _Style } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getPreferences(): Promise<Preferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return from_candid_Preferences_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return from_candid_Preferences_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePreferences(arg0: Style, arg1: IntensityLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreferences(to_candid_Style_n7(this._uploadFile, this._downloadFile, arg0), to_candid_IntensityLevel_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreferences(to_candid_Style_n7(this._uploadFile, this._downloadFile, arg0), to_candid_IntensityLevel_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_IntensityLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntensityLevel): IntensityLevel {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Preferences_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Preferences): Preferences {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Style_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Style): Style {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    style: _Style;
    intensityLevel: _IntensityLevel;
}): {
    style: Style;
    intensityLevel: IntensityLevel;
} {
    return {
        style: from_candid_Style_n3(_uploadFile, _downloadFile, value.style),
        intensityLevel: from_candid_IntensityLevel_n5(_uploadFile, _downloadFile, value.intensityLevel)
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fluent: null;
} | {
    simple: null;
} | {
    eloquent: null;
}): Style {
    return "fluent" in value ? Style.fluent : "simple" in value ? Style.simple : "eloquent" in value ? Style.eloquent : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    normal: null;
} | {
    high: null;
} | {
    extreme: null;
}): IntensityLevel {
    return "low" in value ? IntensityLevel.low : "normal" in value ? IntensityLevel.normal : "high" in value ? IntensityLevel.high : "extreme" in value ? IntensityLevel.extreme : value;
}
function to_candid_IntensityLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntensityLevel): _IntensityLevel {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Style_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Style): _Style {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntensityLevel): {
    low: null;
} | {
    normal: null;
} | {
    high: null;
} | {
    extreme: null;
} {
    return value == IntensityLevel.low ? {
        low: null
    } : value == IntensityLevel.normal ? {
        normal: null
    } : value == IntensityLevel.high ? {
        high: null
    } : value == IntensityLevel.extreme ? {
        extreme: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Style): {
    fluent: null;
} | {
    simple: null;
} | {
    eloquent: null;
} {
    return value == Style.fluent ? {
        fluent: null
    } : value == Style.simple ? {
        simple: null
    } : value == Style.eloquent ? {
        eloquent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
